# Generated by Django 6.1.2 on 2026-10-08 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='approval_priority',
            field=models.CharField(choices=[('low', 'Low Priority'), ('normal', 'Normal'), ('high', 'High Priority'), ('urgent', 'Urgent')], default='normal', help_text='Priority in review queue', max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='approval_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('changes_requested', 'Changes Requested'), ('archived', 'Archived')], db_index=True, default='draft', help_text='Current approval status', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Who added this event (blank for admin-created events)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, help_text='When content was reviewed', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who reviewed this content', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='submitted_at',
            field=models.DateTimeField(blank=True, help_text='When content was submitted for review', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='submitted_by',
            field=models.ForeignKey(blank=True, help_text='User who submitted this content', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_submissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
