# Generated by Django 6.1.2 on 2026-10-08 16:49

from django.db import migrations
from django.utils.text import slugify

# Starter categories so the "add event" form has choices (staff can edit them in
# the admin), and an approval queue so submitted events appear on /approval/.
CATEGORIES = [
    ("Music", "bi-music-note-beamed"), ("Festival", "bi-stars"), ("Sports", "bi-trophy"),
    ("Food & Drink", "bi-cup-hot"), ("Arts & Culture", "bi-palette"), ("Outdoors", "bi-tree"),
    ("Community", "bi-people"), ("Nightlife", "bi-moon-stars"), ("Other", "bi-calendar-event"),
]


def seed(apps, schema_editor):
    EventCategory = apps.get_model("events", "EventCategory")
    for order, (name, icon) in enumerate(CATEGORIES):
        EventCategory.objects.get_or_create(
            name=name, defaults={"slug": slugify(name), "icon": icon, "display_order": order}
        )
    ApprovalQueue = apps.get_model("approval_system", "ApprovalQueue")
    ContentType = apps.get_model("contenttypes", "ContentType")
    queue, _ = ApprovalQueue.objects.get_or_create(
        slug="events",
        defaults={"name": "Events", "description": "User-submitted events", "status_filter": "pending", "icon": "📅"},
    )
    ct, _ = ContentType.objects.get_or_create(app_label="events", model="event")
    queue.content_types.add(ct)


def unseed(apps, schema_editor):
    EventCategory = apps.get_model("events", "EventCategory")
    EventCategory.objects.filter(name__in=[n for n, _ in CATEGORIES], events__isnull=True).delete()
    apps.get_model("approval_system", "ApprovalQueue").objects.filter(slug="events").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_approval_and_creator'),
        ('approval_system', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RunPython(seed, unseed),
    ]
