# Generated by Django 6.1.2 on 2026-10-08 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_alter_activity_specificity_level'),
        ('events', '0003_seed_categories_and_queue'),
        ('locations', '0009_alter_poi_poi_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='country',
            field=models.ForeignKey(blank=True, help_text="Country, when the city isn't in the catalogue", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events_unlinked', to='locations.country'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_text',
            field=models.CharField(blank=True, help_text="City / town as typed by the submitter, when it isn't in the catalogue", max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.ForeignKey(blank=True, help_text="Catalogue city. Leave empty and fill country + location_text if the city isn't listed yet.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='locations.city'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('city__isnull', False), models.Q(('country__isnull', False), models.Q(('location_text', ''), _negated=True)), _connector='OR'), name='event_has_city_or_typed_location'),
        ),
    ]
