# Generated by Django 6.1.1 on 2026-09-29 20:32

import apps.trips.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='destination_timezone',
            field=models.CharField(blank=True, help_text='IANA name for the destination, e.g. America/Denver', max_length=64, validators=[apps.trips.models.validate_timezone_name]),
        ),
        migrations.AddField(
            model_name='flight',
            name='origin_timezone',
            field=models.CharField(blank=True, help_text='IANA name for the origin, e.g. America/New_York', max_length=64, validators=[apps.trips.models.validate_timezone_name]),
        ),
    ]
