# Generated by Django 6.1.1 on 2026-09-29 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_flight_destination_timezone_flight_origin_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('starting', 'Starting'), ('fleshing_out', 'Fleshing out'), ('confirming', 'Confirming'), ('ready_to_go', 'Ready to go')], default='starting', max_length=16),
        ),
        migrations.CreateModel(
            name='BookingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('priority', models.IntegerField(choices=[(1, 'Critical'), (2, 'High'), (3, 'Medium'), (4, 'Low')], default=3)),
                ('due', models.DateField(blank=True, help_text='Hard deadline, if there is one', null=True)),
                ('due_note', models.CharField(blank=True, help_text="Soft deadline or trigger, e.g. 'before Sept 24'", max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('done', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower sorts first within a priority; leave at 0 unless you care')),
                ('confirmation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_tasks', to='trips.confirmation')),
                ('day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_tasks', to='trips.day')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_tasks', to='trips.trip')),
            ],
            options={
                'verbose_name': 'booking task',
                'verbose_name_plural': 'booking tasks',
                'ordering': ['done', 'priority', 'order', 'id'],
                'indexes': [models.Index(fields=['trip', 'done'], name='trips_booki_trip_id_a7fad9_idx')],
            },
        ),
    ]
