# Generated by Django 6.1.1 on 2026-10-07 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0012_traveler_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveler',
            name='bed_preference',
            field=models.CharField(blank=True, choices=[('king', 'King'), ('queen', 'Queen'), ('two_beds', 'Two beds')], max_length=10),
        ),
        migrations.AddField(
            model_name='traveler',
            name='cabin_preference',
            field=models.CharField(blank=True, choices=[('economy', 'Economy'), ('premium_economy', 'Premium economy'), ('business', 'Business'), ('first', 'First')], max_length=20),
        ),
        migrations.AddField(
            model_name='traveler',
            name='known_traveler_number',
            field=models.CharField(blank=True, help_text='TSA PreCheck / Global Entry / NEXUS number.', max_length=25),
        ),
        migrations.AddField(
            model_name='traveler',
            name='meal_preference',
            field=models.CharField(blank=True, choices=[('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('kosher', 'Kosher'), ('halal', 'Halal'), ('gluten_free', 'Gluten-free'), ('diabetic', 'Diabetic'), ('child', 'Child')], help_text='The airline special-meal request. Details go in dietary notes.', max_length=20),
        ),
        migrations.AddField(
            model_name='traveler',
            name='passport_expires',
            field=models.DateField(blank=True, help_text='Many countries require six months left on arrival.', null=True),
        ),
        migrations.AddField(
            model_name='traveler',
            name='passport_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='traveler',
            name='redress_number',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AddField(
            model_name='traveler',
            name='seat_preference',
            field=models.CharField(blank=True, choices=[('aisle', 'Aisle'), ('window', 'Window')], max_length=10),
        ),
        migrations.CreateModel(
            name='RewardsMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('airline', 'Airline'), ('hotel', 'Hotel'), ('rail', 'Rail'), ('car_rental', 'Car rental'), ('credit_card', 'Credit card'), ('other', 'Other')], default='airline', max_length=20)),
                ('program', models.CharField(help_text='e.g. Delta SkyMiles', max_length=120)),
                ('member_number', models.CharField(max_length=40)),
                ('tier', models.CharField(blank=True, help_text='e.g. Gold', max_length=60)),
                ('expires', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='trips.traveler')),
            ],
            options={
                'ordering': ['kind', 'program'],
                'constraints': [models.UniqueConstraint(fields=('traveler', 'program'), name='unique_membership_per_program', violation_error_message='This traveler already has that program.')],
            },
        ),
    ]
