# Generated by Django 6.0 on 2026-01-06 17:31

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bio', models.TextField(blank=True, help_text='Short bio about yourself', max_length=500)),
                ('avatar', models.ImageField(blank=True, help_text='Profile picture', null=True, upload_to='avatars/%Y/%m/')),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='covers/%Y/%m/')),
                ('home_country', models.CharField(blank=True, max_length=100)),
                ('home_city', models.CharField(blank=True, max_length=100)),
                ('current_location', models.CharField(blank=True, help_text='Where you are right now', max_length=100)),
                ('countries_visited_count', models.IntegerField(default=0)),
                ('trips_completed_count', models.IntegerField(default=0)),
                ('bucket_list_completed_count', models.IntegerField(default=0)),
                ('website', models.URLField(blank=True)),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('twitter', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='preferences', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('budget_preference', models.CharField(choices=[('budget', 'Budget Traveler'), ('moderate', 'Moderate'), ('luxury', 'Luxury'), ('mixed', 'Mixed / Flexible')], default='moderate', max_length=20)),
                ('travel_styles', models.JSONField(default=list, help_text='List of preferred travel styles')),
                ('travel_pace', models.CharField(choices=[('slow', 'Slow - Few activities, lots of relaxation'), ('moderate', 'Moderate - Balanced itinerary'), ('fast', 'Fast - Packed schedule, see everything')], default='moderate', max_length=20)),
                ('preferred_activities', models.JSONField(default=list, help_text='List of activity category IDs user prefers')),
                ('fitness_level', models.IntegerField(default=3, help_text='1=Low, 5=Very High', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('mobility_restrictions', models.BooleanField(default=False, help_text='User has mobility restrictions')),
                ('email_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('marketing_emails', models.BooleanField(default=False)),
                ('notify_bucket_list_reminders', models.BooleanField(default=True)),
                ('notify_trip_updates', models.BooleanField(default=True)),
                ('notify_event_reminders', models.BooleanField(default=True)),
                ('notify_friend_activity', models.BooleanField(default=True)),
                ('notify_recommendations', models.BooleanField(default=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('zh', 'Chinese'), ('ja', 'Japanese')], default='en', max_length=5)),
                ('units', models.CharField(choices=[('metric', 'Metric (km, °C)'), ('imperial', 'Imperial (miles, °F)')], default='imperial', max_length=10)),
                ('preferred_currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar')], default='USD', max_length=3)),
            ],
            options={
                'verbose_name': 'User Preference',
                'verbose_name_plural': 'User Preferences',
                'db_table': 'user_preferences',
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='Premium subscription status'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Email verification status'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='premium_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_visibility',
            field=models.CharField(choices=[('public', 'Public'), ('friends', 'Friends Only'), ('private', 'Private')], default='public', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Required. A valid email address.', max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
