# Generated by Django 6.0.1 on 2026-01-22 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_migration_existing_users'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='rolerequest',
            new_name='role_reques_user_id_d3ddac_idx',
            old_name='role_reques_user_id_a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='rolerequest',
            new_name='role_reques_status_75dc0c_idx',
            old_name='role_reques_status_d4e5f6_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_premium',
        ),
        migrations.RemoveField(
            model_name='user',
            name='premium_expires',
        ),
    ]
