# Generated by Django 6.0.1 on 2026-01-24 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_role_reques_user_id_a1b2c3_idx_role_reques_user_id_d3ddac_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsettings',
            name='preferred_currency',
            field=models.CharField(default='USD', help_text='ISO currency code (e.g., USD, EUR, GBP). Should match a currency from the Country model.', max_length=3),
        ),
    ]
