# Generated by Django 6.0.1 on 2026-01-31 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_alter_activity_risk_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('shared', 'Shared')], default='private', help_text='Who can see this activity', max_length=20),
        ),
    ]
