# Generated by Django 6.0.1 on 2026-01-31 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_alter_activity_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='specificity_level',
            field=models.CharField(choices=[('general', 'General - no details'), ('specific', 'Specific - some details'), ('very_specific', 'Very Specific - most details')], default='general', help_text='How specific is this activity description?', max_length=20),
        ),
    ]
