# Generated by Django 6.0 on 2026-01-06 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_userpreferences_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='timezone',
            field=models.CharField(default='UTC', help_text='IANA timezone (e.g. America/New_York)', max_length=50),
        ),
    ]
