# Generated by Django 6.0.1 on 2026-01-15 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userpreferences_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='theme',
            field=models.CharField(choices=[('default', 'System Default'), ('light', 'Light'), ('dark', 'Dark')], default='default', help_text='UI theme preference', max_length=10),
        ),
    ]
