# Generated by Django 6.0.1 on 2026-01-15 02:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userpreferences_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='settings', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('email_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('marketing_emails', models.BooleanField(default=False)),
                ('notify_bucket_list_reminders', models.BooleanField(default=True)),
                ('notify_trip_updates', models.BooleanField(default=True)),
                ('notify_event_reminders', models.BooleanField(default=True)),
                ('notify_friend_activity', models.BooleanField(default=True)),
                ('notify_recommendations', models.BooleanField(default=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('zh', 'Chinese'), ('ja', 'Japanese')], default='en', max_length=5)),
                ('units', models.CharField(choices=[('metric', 'Metric (km, °C)'), ('imperial', 'Imperial (miles, °F)')], default='imperial', max_length=10)),
                ('preferred_currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar')], default='USD', max_length=3)),
                ('timezone', models.CharField(default='UTC', help_text='IANA timezone (e.g. America/New_York)', max_length=50)),
                ('theme', models.CharField(choices=[('default', 'System Default'), ('light', 'Light'), ('dark', 'Dark')], default='default', help_text='UI theme preference', max_length=10)),
                ('show_email_on_profile', models.BooleanField(default=False, help_text='Display email address on public profile')),
                ('show_trips_publicly', models.BooleanField(default=True, help_text='Allow others to see your trips')),
                ('allow_friend_requests', models.BooleanField(default=True, help_text='Allow others to send friend requests')),
            ],
            options={
                'verbose_name': 'Account Settings',
                'verbose_name_plural': 'Account Settings',
                'db_table': 'account_settings',
            },
        ),
        migrations.CreateModel(
            name='TravelPreferences',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='travel_preferences', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('budget_preference', models.CharField(choices=[('budget', 'Budget Traveler'), ('moderate', 'Moderate'), ('luxury', 'Luxury'), ('mixed', 'Mixed / Flexible')], default='moderate', max_length=20)),
                ('travel_styles', models.JSONField(default=list, help_text='List of preferred travel styles')),
                ('travel_pace', models.CharField(choices=[('slow', 'Slow - Few activities, lots of relaxation'), ('moderate', 'Moderate - Balanced itinerary'), ('fast', 'Fast - Packed schedule, see everything')], default='moderate', max_length=20)),
                ('preferred_activities', models.JSONField(default=list, help_text='List of activity category IDs user prefers')),
                ('fitness_level', models.IntegerField(default=3, help_text='1=Low, 5=Very High', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('mobility_restrictions', models.BooleanField(default=False, help_text='User has mobility restrictions')),
            ],
            options={
                'verbose_name': 'Travel Preference',
                'verbose_name_plural': 'Travel Preferences',
                'db_table': 'travel_preferences',
            },
        ),
        migrations.AlterModelOptions(
            name='userpreferences',
            options={'verbose_name': 'User Preference (Deprecated)', 'verbose_name_plural': 'User Preferences (Deprecated)'},
        ),
    ]
