# Generated by Django 6.0.1 on 2026-01-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_split_userpreferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsettings',
            name='theme',
            field=models.CharField(choices=[('brand', 'ShareBucketList Theme'), ('light', 'Light'), ('dark', 'Dark')], default='brand', help_text='UI theme preference', max_length=10),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='theme',
            field=models.CharField(choices=[('brand', 'ShareBucketList Theme'), ('light', 'Light'), ('dark', 'Dark')], default='brand', help_text='UI theme preference', max_length=10),
        ),
    ]
