# Generated by Django 6.0.1 on 2026-01-16 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_accountsettings_theme_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_access_staff_dashboard', 'Can access staff dashboard')], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
