# Generated by Django 6.1.2 on 2026-10-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_userrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('creator', 'Creator')], max_length=16),
        ),
    ]
