# Generated by Django 6.0.1 on 2026-01-22 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='capital_type',
            field=models.CharField(blank=True, choices=[('country', 'Country capital'), ('region', 'Region/State capital'), ('both', 'Country and Region capital')], help_text='Capital level for this city', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='elevation',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Elevation of the City in feet', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='is_capital',
            field=models.BooleanField(blank=True, default=False, help_text='Is this a capital city.  It can be the capital of the country or region/state', null=True),
        ),
    ]
