# Generated by Django 6.0.1 on 2026-01-30 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_remove_city_poi_count_remove_country_city_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poi',
            name='poi_type',
            field=models.CharField(choices=[('landmark', 'Landmark'), ('museum', 'Museum'), ('park', 'Park/Garden'), ('beach', 'Beach'), ('mountain', 'Mountain'), ('temple', 'Temple/Religious Site'), ('historical', 'Historical Site'), ('viewpoint', 'Viewpoint'), ('entertainment', 'Entertainment'), ('shopping', 'Shopping'), ('nightlife', 'Nightlife'), ('nature', 'Nature Reserve'), ('sports', 'Sports Venues'), ('other', 'Other')], default='landmark', max_length=20),
        ),
    ]
