# Generated by Django 6.0 on 2026-01-06 21:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('events', '0001_initial'),
        ('locations', '0001_initial'),
        ('trips', '0001_initial'),
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review_type', models.CharField(choices=[('vendor', 'Vendor'), ('activity', 'Activity'), ('event', 'Event'), ('location', 'Location'), ('trip', 'Trip'), ('site', 'Website Feedback')], db_index=True, max_length=20)),
                ('rating', models.IntegerField(help_text='Rating from 1 to 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(blank=True, help_text='Review title/headline', max_length=200)),
                ('comment', models.TextField(help_text='Detailed review')),
                ('value_rating', models.IntegerField(blank=True, help_text='Value for money', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('service_rating', models.IntegerField(blank=True, help_text='Service quality', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('cleanliness_rating', models.IntegerField(blank=True, help_text='Cleanliness (for accommodations)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('difficulty_rating', models.IntegerField(blank=True, help_text='Difficulty level (1=easy, 5=very hard)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('visit_date', models.DateField(blank=True, help_text='When did you visit/experience this?', null=True)),
                ('travel_type', models.CharField(blank=True, choices=[('solo', 'Solo'), ('couple', 'Couple'), ('family', 'Family'), ('friends', 'Friends'), ('business', 'Business')], max_length=20)),
                ('pros', models.TextField(blank=True, help_text='What you liked')),
                ('cons', models.TextField(blank=True, help_text='What could be improved')),
                ('tips', models.TextField(blank=True, help_text='Tips for future visitors')),
                ('site_feedback_category', models.CharField(blank=True, choices=[('ui_ux', 'User Interface/Design'), ('feature', 'Feature Request'), ('bug', 'Bug Report'), ('performance', 'Speed/Performance'), ('general', 'General Feedback')], max_length=20)),
                ('is_verified_visit', models.BooleanField(default=False, help_text='User verified they actually visited/experienced this')),
                ('is_approved', models.BooleanField(default=True, help_text='Approved by moderators')),
                ('is_featured', models.BooleanField(default=False, help_text='Featured review (highlighted)')),
                ('is_flagged', models.BooleanField(default=False)),
                ('flagged_reason', models.TextField(blank=True)),
                ('helpful_count', models.IntegerField(default=0, help_text='Number of users who found this helpful')),
                ('report_count', models.IntegerField(default=0, help_text='Number of times reported')),
                ('has_response', models.BooleanField(default=False)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='activities.activity')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='events.event')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='locations.city')),
                ('trip', models.ForeignKey(blank=True, help_text="For reviewing someone else's public trip itinerary", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='trips.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='vendors.vendor')),
            ],
            options={
                'db_table': 'reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewHelpful',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_helpful', models.BooleanField(default=True, help_text='True if helpful, False if not helpful')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpful_votes', to='reviews.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpful_review_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'review_helpful',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('offensive', 'Offensive Language'), ('fake', 'Fake Review'), ('irrelevant', 'Irrelevant Content'), ('personal', 'Personal Information'), ('other', 'Other')], max_length=20)),
                ('details', models.TextField(blank=True, help_text='Additional details about the report')),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_reports', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_reports', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='reviews.review')),
            ],
            options={
                'db_table': 'review_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responder_type', models.CharField(choices=[('owner', 'Business Owner'), ('manager', 'Manager'), ('admin', 'Site Admin'), ('staff', 'Staff Member')], default='owner', max_length=20)),
                ('response_text', models.TextField()),
                ('is_approved', models.BooleanField(default=True, help_text='Response approved by moderators')),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_responses', to=settings.AUTH_USER_MODEL)),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='reviews.review')),
            ],
            options={
                'db_table': 'review_responses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user', '-created_at'], name='reviews_user_id_9f7b05_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['review_type', '-created_at'], name='reviews_review__ec6094_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['rating', '-created_at'], name='reviews_rating_61536a_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['is_approved', '-created_at'], name='reviews_is_appr_48b62f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'activity'), ('user', 'event'), ('user', 'location'), ('user', 'trip'), ('user', 'vendor')},
        ),
        migrations.AlterUniqueTogether(
            name='reviewhelpful',
            unique_together={('review', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='reviewreport',
            unique_together={('review', 'reporter')},
        ),
    ]
