# Generated by Django 6.1.2 on 2026-10-08 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bucketlists', '0001_initial'),
        ('locations', '0009_alter_poi_poi_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucketlistitem',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='items', through='bucketlists.BucketListItemCategory', to='bucketlists.bucketlistcategory'),
        ),
        migrations.AddField(
            model_name='bucketlistitem',
            name='poi',
            field=models.ForeignKey(blank=True, help_text='Place / point of interest to visit', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bucket_list_items', to='locations.poi'),
        ),
        migrations.AlterField(
            model_name='bucketlistitem',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Show on your public bucket list page'),
        ),
    ]
