# Generated by Django 6.0.1 on 2026-01-15 17:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rewardsprogram',
            name='rewards_program_unique_name_company',
        ),
        migrations.RemoveConstraint(
            model_name='userrewardsmembership',
            name='user_rewards_unique_user_program',
        ),
        migrations.RenameIndex(
            model_name='rewardsprogram',
            new_name='rewards_pro_program_355b69_idx',
            old_name='rewards_pro_program_idx',
        ),
        migrations.RenameIndex(
            model_name='rewardsprogram',
            new_name='rewards_pro_display_d13152_idx',
            old_name='rewards_pro_display_idx',
        ),
        migrations.RenameIndex(
            model_name='userrewardsmembership',
            new_name='user_reward_user_id_94eb2e_idx',
            old_name='user_reward_user_id_primary_idx',
        ),
        migrations.RenameIndex(
            model_name='userrewardsmembership',
            new_name='user_reward_user_id_5d1b20_idx',
            old_name='user_reward_user_id_profile_idx',
        ),
        migrations.RenameIndex(
            model_name='userrewardsmembership',
            new_name='user_reward_user_id_109b0c_idx',
            old_name='user_reward_user_id_program_idx',
        ),
        migrations.AlterField(
            model_name='rewardsprogram',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='userrewardsmembership',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterUniqueTogether(
            name='rewardsprogram',
            unique_together={('name', 'company')},
        ),
        migrations.AlterUniqueTogether(
            name='userrewardsmembership',
            unique_together={('user', 'program')},
        ),
    ]
