# Generated by Django 6.0 on 2026-01-06 21:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(help_text='URL-friendly version of the name', max_length=255, unique=True)),
                ('name', models.CharField(help_text='E.g., Accommodation, Dining, Tours, Transportation', max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Icon name or emoji', max_length=50)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Vendor Categories',
                'db_table': 'vendor_categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(help_text='URL-friendly version of the name', max_length=255, unique=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False, help_text='Featured in suggested content catalog')),
                ('featured_order', models.IntegerField(default=0, help_text='Display order for featured content (higher = more prominent)')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('booking_url', models.URLField(blank=True, help_text='Direct booking link')),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('facebook', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(help_text='Detailed description of the vendor')),
                ('short_description', models.CharField(blank=True, help_text='Brief description for cards/lists', max_length=300)),
                ('price_range', models.CharField(choices=[('budget', '$ - Budget'), ('moderate', '$$ - Moderate'), ('upscale', '$$$ - Upscale'), ('luxury', '$$$$ - Luxury')], default='moderate', max_length=20)),
                ('average_price', models.DecimalField(blank=True, decimal_places=2, help_text='Average price per night/meal/tour in local currency', max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', help_text='Currency code for prices', max_length=3)),
                ('opening_hours', models.JSONField(blank=True, default=dict, help_text="Operating hours by day of week: {'monday': '9:00-17:00', ...}")),
                ('seasonal_closure', models.TextField(blank=True, help_text='Information about seasonal closures')),
                ('booking_required', models.BooleanField(default=False, help_text='Whether booking/reservation is required')),
                ('accepts_walk_ins', models.BooleanField(default=True)),
                ('capacity', models.IntegerField(blank=True, help_text='Max capacity (rooms for hotels, seats for tours, etc.)', null=True)),
                ('accepts_credit_cards', models.BooleanField(default=True)),
                ('accepts_cash', models.BooleanField(default=True)),
                ('payment_methods', models.JSONField(blank=True, default=list, help_text='List of accepted payment methods')),
                ('languages_spoken', models.JSONField(blank=True, default=list, help_text="List of language codes: ['en', 'es', 'fr']")),
                ('is_verified', models.BooleanField(default=False, help_text='Verified by admin/moderators')),
                ('verified_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether vendor is currently operating')),
                ('is_partner', models.BooleanField(default=False, help_text='Official partner with special benefits')),
                ('claimed_by_owner', models.BooleanField(default=False, help_text='Whether business owner has claimed this listing')),
                ('review_count', models.IntegerField(default=0)),
                ('average_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('booking_count', models.IntegerField(default=0, help_text='Number of bookings through platform')),
                ('view_count', models.IntegerField(default=0)),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description', max_length=160)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='locations.city')),
                ('poi', models.ForeignKey(blank=True, help_text='If vendor is located at/near a specific POI', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors', to='locations.poi')),
            ],
            options={
                'db_table': 'vendors',
                'ordering': ['-is_featured', '-average_rating', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VendorAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('general', 'General'), ('accommodation', 'Accommodation'), ('dining', 'Dining'), ('accessibility', 'Accessibility'), ('technology', 'Technology'), ('recreation', 'Recreation'), ('services', 'Services')], default='general', max_length=20)),
                ('name', models.CharField(help_text='E.g., WiFi, Pool, Parking, Pet Friendly', max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('is_premium', models.BooleanField(default=False, help_text='Premium amenity (highlighted in listings)')),
                ('display_order', models.IntegerField(default=0)),
                ('vendors', models.ManyToManyField(blank=True, related_name='amenities', to='vendors.vendor')),
            ],
            options={
                'verbose_name_plural': 'Vendor Amenities',
                'db_table': 'vendor_amenities',
                'ordering': ['category', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VendorContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, help_text='E.g., Manager, Owner, Marketing Director', max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary contact for this vendor')),
                ('notes', models.TextField(blank=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='vendors.vendor')),
            ],
            options={
                'db_table': 'vendor_contacts',
                'ordering': ['-is_primary', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VendorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(help_text='URL-friendly version of the name', max_length=255, unique=True)),
                ('name', models.CharField(help_text='E.g., Hotel, Hostel, Restaurant, Tour Operator', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='vendors.vendorcategory')),
            ],
            options={
                'db_table': 'vendor_types',
                'ordering': ['category', 'name'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendors', to='vendors.vendortype'),
        ),
        migrations.CreateModel(
            name='VendorHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('is_closed', models.BooleanField(default=False)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('second_opening_time', models.TimeField(blank=True, null=True)),
                ('second_closing_time', models.TimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, help_text="E.g., 'Happy hour 5-7pm'", max_length=200)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_hours', to='vendors.vendor')),
            ],
            options={
                'db_table': 'vendor_hours',
                'ordering': ['vendor', 'day_of_week'],
                'unique_together': {('vendor', 'day_of_week')},
            },
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['city', 'vendor_type'], name='vendors_city_id_6caca9_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['-average_rating'], name='vendors_average_a43f4a_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['is_verified', 'is_active'], name='vendors_is_veri_66e544_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['latitude', 'longitude'], name='vendors_latitud_6929a6_idx'),
        ),
    ]
