"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# The fallback is for local development only; prod.py refuses to start without
# a real DJANGO_SECRET_KEY. (This read "DJANGO_SECERT_KEY" until the
# prod-readiness branch, so the .env value was silently ignored.)
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "django-insecure-dev-only-not-for-production")

# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = os.getenv("DJANGO_DEBUG", "False").lower() in ("true", "1", "yes")
ALLOWED_HOSTS = [h.strip() for h in os.getenv("DJANGO_ALLOWED_HOSTS", "").split(",") if h.strip()]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize', 
    'widget_tweaks',
    'taggit',
    'crispy_forms',
    'crispy_bootstrap5',
    
    # local apps 
    'apps.core',
    'apps.accounts',
    'apps.locations',
    'apps.activities',
    'apps.vendors',
    'apps.events',
    'apps.media_app',
    'apps.bucketlists',
    'apps.trips',
    'apps.reviews',
    'apps.notifications',
    'apps.recommendations',
    'apps.admin_tools',
    'apps.rewards',
    'apps.approval_system',
    'apps.pages',
    'theme',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'apps.core.middleware.UserTimezoneMiddleware',
    'apps.core.middleware.UserThemeMiddleware',
]

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        "LOCATION": "unique-snowflake", # Optional location identifier

    }
}
ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"], 
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "apps.core.context_processors.site_branding",   
                "apps.core.context_processors.user_settings",
                "apps.core.context_processors.user_preferences",                             
                "apps.rewards.context_processors.rewards_context",
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': BASE_DIR / 'db.sqlite3',
#    }
#}

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("POSTGRES_DB", "travelsite"),
        "USER": os.environ.get("POSTGRES_USER", "travelappuser"),
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD", ""),
        "HOST": os.environ.get("POSTGRES_HOST", "127.0.0.1"),
        "PORT": os.environ.get("POSTGRES_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Authentication backends
AUTHENTICATION_BACKENDS = [
    'apps.accounts.backends.EmailOrUsernameBackend',  # NEW - allows email or username login
    'django.contrib.auth.backends.ModelBackend',  # Keep as fallback
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "uploads"

AUTH_USER_MODEL = 'accounts.User'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'pages:dashboard'
LOGOUT_REDIRECT_URL = 'pages:home'

# Outgoing mail. Every value comes from the environment (.env), so each machine
# can use its own provider; credentials never go in code. dev.py / prod.py pick
# EMAIL_BACKEND, and prod.py requires EMAIL_HOST to be set explicitly.
def _env_flag(name, default):
    return os.environ.get(name, default).lower() in ("true", "1", "yes")


EMAIL_HOST = os.environ.get("EMAIL_HOST", "localhost")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
EMAIL_USE_TLS = _env_flag("EMAIL_USE_TLS", "True")    # STARTTLS, usually port 587
EMAIL_USE_SSL = _env_flag("EMAIL_USE_SSL", "False")   # implicit TLS, usually port 465
if EMAIL_USE_TLS and EMAIL_USE_SSL:
    from django.core.exceptions import ImproperlyConfigured
    raise ImproperlyConfigured("Set only one of EMAIL_USE_TLS / EMAIL_USE_SSL (port 587 -> TLS, 465 -> SSL).")
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
EMAIL_TIMEOUT = int(os.environ.get("EMAIL_TIMEOUT", "10"))
# The provider may only accept a From address on a domain verified with it.
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "no-reply@sharebucketlist.com")
SERVER_EMAIL = os.environ.get("SERVER_EMAIL", DEFAULT_FROM_EMAIL)  # sender of error mails to ADMINS

SITE_NAME = 'ShareBucketList'
SITE_TAGLINE = 'Plan it. Live it. Share it.'

# Details used by the Terms, Privacy and Safety pages (apps/pages, templates under
# pages/legal/). Set them in .env; while any is still a [bracketed] placeholder the
# pages show a "draft" banner. Have the wording reviewed before public launch.
LEGAL = {
    "entity": os.environ.get("LEGAL_ENTITY_NAME", "[Legal entity name]"),
    "contact_email": os.environ.get("LEGAL_CONTACT_EMAIL", "[privacy@your-domain]"),
    "postal_address": os.environ.get("LEGAL_POSTAL_ADDRESS", "[Postal address]"),
    "jurisdiction": os.environ.get("LEGAL_JURISDICTION", "[State / country whose law governs]"),
    "effective_date": os.environ.get("LEGAL_EFFECTIVE_DATE", "[Effective date]"),
    "min_age": os.environ.get("LEGAL_MIN_AGE", "16"),
}

# The 'theme' app (installed here) ships the built CSS that collectstatic gathers.
# The 'tailwind' app that can rebuild it is installed only in dev.py.
TAILWIND_APP_NAME = 'theme'
