# Generated by Django 6.0 on 2026-01-07 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_users', models.IntegerField(default=0)),
                ('new_users_today', models.IntegerField(default=0)),
                ('active_users_today', models.IntegerField(default=0)),
                ('premium_users', models.IntegerField(default=0)),
                ('total_trips', models.IntegerField(default=0)),
                ('trips_created_today', models.IntegerField(default=0)),
                ('total_bucket_list_items', models.IntegerField(default=0)),
                ('bucket_list_items_added_today', models.IntegerField(default=0)),
                ('total_reviews', models.IntegerField(default=0)),
                ('reviews_created_today', models.IntegerField(default=0)),
                ('total_page_views', models.BigIntegerField(default=0)),
                ('total_sessions', models.IntegerField(default=0)),
                ('avg_session_duration', models.IntegerField(default=0, help_text='Average session duration in seconds')),
                ('total_activities', models.IntegerField(default=0)),
                ('total_events', models.IntegerField(default=0)),
                ('total_locations', models.IntegerField(default=0)),
                ('total_vendors', models.IntegerField(default=0)),
                ('pending_moderation_count', models.IntegerField(default=0)),
                ('reports_resolved_today', models.IntegerField(default=0)),
                ('avg_response_time', models.IntegerField(default=0, help_text='Average API response time in milliseconds')),
                ('error_count', models.IntegerField(default=0, help_text='Number of errors today')),
                ('revenue_today', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('custom_metrics', models.JSONField(blank=True, default=dict, help_text='Additional custom metrics')),
            ],
            options={
                'verbose_name_plural': 'System Metrics',
                'db_table': 'system_metrics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AdminAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.CharField(choices=[('user_ban', 'User Ban'), ('user_unban', 'User Unban'), ('content_remove', 'Content Remove'), ('content_restore', 'Content Restore'), ('feature_flag', 'Feature Flag Change'), ('config_change', 'Configuration Change'), ('data_export', 'Data Export'), ('bulk_action', 'Bulk Action'), ('other', 'Other')], db_index=True, max_length=20)),
                ('description', models.TextField(help_text='Description of action taken')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('before_state', models.JSONField(blank=True, default=dict, help_text='State before action')),
                ('after_state', models.JSONField(blank=True, default=dict, help_text='State after action')),
                ('reason', models.TextField(blank=True, help_text='Reason for taking this action')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'admin_actions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['admin', '-created_at'], name='admin_actio_admin_i_3b7b37_idx'), models.Index(fields=['action_type', '-created_at'], name='admin_actio_action__70c639_idx')],
            },
        ),
        migrations.CreateModel(
            name='ModerationQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('reason', models.CharField(choices=[('new_content', 'New Content Review'), ('user_report', 'User Report'), ('auto_flag', 'Automatic Flag'), ('policy_violation', 'Policy Violation'), ('spam_detection', 'Spam Detection'), ('quality_check', 'Quality Check')], max_length=20)),
                ('reason_details', models.TextField(blank=True, help_text='Additional details about why this needs moderation')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='normal', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('escalated', 'Escalated')], db_index=True, default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('action_taken', models.CharField(blank=True, help_text='Action taken by moderator', max_length=100)),
                ('escalation_reason', models.TextField(blank=True)),
                ('content_type', models.ForeignKey(help_text='Type of content (Review, Media, etc.)', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('escalated_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_moderations', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_reviews', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_for_moderation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'moderation_queue',
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='moderation__status_30d459_idx'), models.Index(fields=['priority', 'status'], name='moderation__priorit_fe6c38_idx'), models.Index(fields=['content_type', 'object_id'], name='moderation__content_a93b02_idx'), models.Index(fields=['reviewed_by'], name='moderation__reviewe_eb5fb1_idx')],
            },
        ),
        migrations.CreateModel(
            name='ModeratorNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('note', models.TextField()),
                ('is_internal', models.BooleanField(default=True, help_text='Only visible to moderators')),
                ('is_pinned', models.BooleanField(default=False, help_text='Pin this note for visibility')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderator_notes', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'moderator_notes',
                'ordering': ['-is_pinned', '-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='moderator_n_content_3d5a94_idx'), models.Index(fields=['-created_at'], name='moderator_n_created_c00513_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReportedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Harassment'), ('hate_speech', 'Hate Speech'), ('violence', 'Violence'), ('nudity', 'Nudity/Sexual Content'), ('false_info', 'False Information'), ('copyright', 'Copyright Violation'), ('personal_info', 'Sharing Personal Information'), ('scam', 'Scam/Fraud'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(help_text='Detailed description of the issue')),
                ('evidence_urls', models.JSONField(blank=True, default=list, help_text='URLs to screenshots or evidence')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('investigating', 'Under Investigation'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed'), ('escalated', 'Escalated')], db_index=True, default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('action_taken', models.CharField(blank=True, help_text='What action was taken', max_length=200)),
                ('requires_followup', models.BooleanField(default=False)),
                ('followup_notes', models.TextField(blank=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_reports', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reported_content',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='reported_co_status_ad5596_idx'), models.Index(fields=['reporter', '-created_at'], name='reported_co_reporte_e82c74_idx'), models.Index(fields=['content_type', 'object_id'], name='reported_co_content_a93cfd_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View'), ('download', 'Download'), ('share', 'Share'), ('report', 'Report'), ('review', 'Review'), ('booking', 'Booking'), ('payment', 'Payment'), ('other', 'Other')], db_index=True, max_length=20)),
                ('action_description', models.CharField(help_text='Brief description of action', max_length=300)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context data')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_activity_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='user_activi_user_id_543519_idx'), models.Index(fields=['action_type', '-created_at'], name='user_activi_action__1fe201_idx'), models.Index(fields=['-created_at'], name='user_activi_created_66afa1_idx')],
            },
        ),
    ]
