# Generated by Django 6.0 on 2026-01-06 21:20

import django.db.models.deletion
import media_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='E.g., Trip Photos, Reviews, Profile Pictures, Activity Images', max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_system_category', models.BooleanField(default=False, help_text='System-reserved category')),
            ],
            options={
                'verbose_name_plural': 'Media Categories',
                'db_table': 'media_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(max_length=500, upload_to=media_app.models.user_media_upload_path)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document'), ('audio', 'Audio')], db_index=True, max_length=20)),
                ('file_size', models.BigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('file_extension', models.CharField(blank=True, max_length=10)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, help_text='Video duration in seconds', null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/%Y/%m/')),
                ('is_user_generated', models.BooleanField(default=True, help_text='True for user uploads, False for site/admin content')),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='ID of the object this media is attached to', null=True)),
                ('title', models.CharField(blank=True, help_text='Optional title for the media', max_length=200)),
                ('caption', models.TextField(blank=True, help_text='Caption or description')),
                ('alt_text', models.CharField(blank=True, help_text='Alt text for accessibility', max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_name', models.CharField(blank=True, help_text='Named location where photo was taken', max_length=200)),
                ('taken_at', models.DateTimeField(blank=True, help_text='When photo/video was taken', null=True)),
                ('tags', models.JSONField(blank=True, default=list, help_text='List of tags for this media')),
                ('privacy', models.CharField(choices=[('public', 'Public'), ('friends', 'Friends Only'), ('private', 'Private')], default='public', max_length=20)),
                ('is_featured', models.BooleanField(default=False, help_text='Featured in galleries/homepage')),
                ('is_approved', models.BooleanField(default=True, help_text='Approved by moderators')),
                ('is_flagged', models.BooleanField(default=False, help_text='Flagged for review')),
                ('flagged_reason', models.TextField(blank=True)),
                ('display_order', models.IntegerField(default=0, help_text='Order in galleries/albums')),
                ('view_count', models.IntegerField(default=0)),
                ('download_count', models.IntegerField(default=0)),
                ('like_count', models.IntegerField(default=0)),
                ('storage_backend', models.CharField(default='local', help_text='Storage backend (local, s3, cloudinary, etc.)', max_length=50)),
                ('content_type', models.ForeignKey(blank=True, help_text='Type of object this media is attached to', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_media', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_files', to='media_app.mediacategory')),
            ],
            options={
                'verbose_name_plural': 'Media',
                'db_table': 'media',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('privacy', models.CharField(choices=[('public', 'Public'), ('friends', 'Friends Only'), ('private', 'Private')], default='public', max_length=20)),
                ('media_count', models.IntegerField(default=0)),
                ('view_count', models.IntegerField(default=0)),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_for_albums', to='media_app.media')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_albums', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'media_albums',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlbumMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_order', models.IntegerField(default=0)),
                ('caption', models.TextField(blank=True, help_text='Album-specific caption (overrides media caption)')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_memberships', to='media_app.media')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_media_items', to='media_app.mediaalbum')),
            ],
            options={
                'db_table': 'album_media',
                'ordering': ['album', 'display_order'],
                'unique_together': {('album', 'media')},
            },
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['uploaded_by', '-created_at'], name='media_uploade_07bcc6_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['content_type', 'object_id'], name='media_content_a5c40c_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['media_type', 'is_approved'], name='media_media_t_ff36bc_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['-created_at'], name='media_created_8cc717_idx'),
        ),
    ]
