# Generated by Django 6.0.1 on 2026-01-15 19:32

import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediaalbum',
            name='media_count',
        ),
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.CharField(blank=True, choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document'), ('audio', 'Audio')], db_index=True, max_length=20),
        ),
        migrations.RemoveField(
            model_name='media',
            name='tags',
        ),
        migrations.AddField(
            model_name='media',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
