# Generated by Django 6.0.1 on 2026-01-25 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_on_submission', models.BooleanField(default=True, help_text='Notify reviewers when new items are submitted')),
                ('notify_on_approval', models.BooleanField(default=True, help_text='Notify submitters when items are approved')),
                ('notify_on_rejection', models.BooleanField(default=True, help_text='Notify submitters when items are rejected')),
                ('auto_archive_rejected_days', models.IntegerField(default=30, help_text='Auto-archive rejected items after X days (0 = never)')),
                ('review_sla_hours', models.IntegerField(default=48, help_text='Expected review time in hours (for metrics)')),
                ('items_per_page', models.IntegerField(default=25)),
                ('show_archived_in_search', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Approval Settings',
                'verbose_name_plural': 'Approval Settings',
                'db_table': 'approval_settings',
            },
        ),
        migrations.CreateModel(
            name='ApprovalQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(unique=True)),
                ('status_filter', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('changes_requested', 'Changes Requested'), ('archived', 'Archived')], default='pending', help_text='Show items with this status', max_length=20)),
                ('priority_filter', models.CharField(blank=True, choices=[('low', 'Low Priority'), ('normal', 'Normal'), ('high', 'High Priority'), ('urgent', 'Urgent')], help_text='Show items with this priority (blank = all)', max_length=10)),
                ('color', models.CharField(default='#007bff', help_text='Color for queue badge (hex)', max_length=7)),
                ('icon', models.CharField(blank=True, help_text='Icon class or emoji', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('content_types', models.ManyToManyField(help_text='Types of content in this queue', to='contenttypes.contenttype')),
                ('reviewers', models.ManyToManyField(blank=True, help_text='Staff members assigned to this queue', related_name='approval_queues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'approval_queues',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority rules are evaluated first')),
                ('auto_approve', models.BooleanField(default=False, help_text='Automatically approve if conditions met')),
                ('auto_reject', models.BooleanField(default=False, help_text='Automatically reject if conditions met')),
                ('conditions', models.JSONField(default=dict, help_text='Conditions that must be met for this rule to apply')),
                ('assign_to_user', models.ForeignKey(blank=True, help_text='Assign matching items to this reviewer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_approvals', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(help_text='Type of content this rule applies to', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'approval_rules',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('submitted', 'Submitted for Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('changes_requested', 'Changes Requested'), ('archived', 'Archived'), ('edited', 'Edited'), ('priority_changed', 'Priority Changed')], max_length=20)),
                ('old_status', models.CharField(blank=True, choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('changes_requested', 'Changes Requested'), ('archived', 'Archived')], max_length=20, null=True)),
                ('new_status', models.CharField(blank=True, choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('changes_requested', 'Changes Requested'), ('archived', 'Archived')], max_length=20, null=True)),
                ('notes', models.TextField(blank=True, help_text='Reason or comments')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional data (changed fields, etc.)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'approval_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='approval_lo_content_080138_idx'), models.Index(fields=['performed_by', '-created_at'], name='approval_lo_perform_8833c0_idx'), models.Index(fields=['action', '-created_at'], name='approval_lo_action_392e20_idx')],
            },
        ),
    ]
