# Generated by Django 6.0 on 2026-01-06 17:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(help_text='URL-friendly version of the name', max_length=255, unique=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False, help_text='Featured in suggested content catalog')),
                ('featured_order', models.IntegerField(default=0, help_text='Display order for featured content (higher = more prominent)')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('iso_code', models.CharField(help_text='ISO 3166-1 alpha-2 code', max_length=2, unique=True)),
                ('iso3_code', models.CharField(help_text='ISO 3166-1 alpha-3 code', max_length=3, unique=True)),
                ('continent', models.CharField(choices=[('Africa', 'Africa'), ('Antarctica', 'Antarctica'), ('Asia', 'Asia'), ('Europe', 'Europe'), ('North America', 'North America'), ('Oceania', 'Oceania'), ('South America', 'South America')], max_length=50)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('currency_code', models.CharField(blank=True, max_length=3)),
                ('currency_name', models.CharField(blank=True, max_length=50)),
                ('phone_code', models.CharField(blank=True, max_length=10)),
                ('flag_emoji', models.CharField(blank=True, max_length=10)),
                ('description', models.TextField(blank=True)),
                ('travel_tips', models.TextField(blank=True, help_text='General travel tips for this country')),
                ('visa_required', models.BooleanField(default=True, help_text='General visa requirement info')),
                ('visa_info', models.TextField(blank=True, help_text='Visa requirements details')),
                ('city_count', models.IntegerField(default=0)),
                ('poi_count', models.IntegerField(default=0)),
                ('visitor_count', models.IntegerField(default=0, help_text='Number of users who visited')),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'db_table': 'locations_countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(help_text='URL-friendly version of the name', max_length=255, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, help_text='State/Province code (e.g., CA for California)', max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('description', models.TextField(blank=True)),
                ('city_count', models.IntegerField(default=0)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='locations.country')),
            ],
            options={
                'db_table': 'locations_regions',
                'ordering': ['country', 'name'],
                'unique_together': {('country', 'name')},
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(help_text='URL-friendly version of the name', max_length=255, unique=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False, help_text='Featured in suggested content catalog')),
                ('featured_order', models.IntegerField(default=0, help_text='Display order for featured content (higher = more prominent)')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, help_text='City center coordinates', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='City center coordinates', max_digits=9)),
                ('timezone', models.CharField(blank=True, help_text='IANA timezone (e.g., America/New_York)', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('best_time_to_visit', models.CharField(blank=True, help_text="E.g., 'Spring (March-May) and Fall (Sept-Nov)'", max_length=200)),
                ('average_daily_budget', models.DecimalField(blank=True, decimal_places=2, help_text='Average daily budget in USD', max_digits=8, null=True)),
                ('poi_count', models.IntegerField(default=0)),
                ('visitor_count', models.IntegerField(default=0)),
                ('average_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('review_count', models.IntegerField(default=0)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='locations.country')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cities', to='locations.region')),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'db_table': 'locations_cities',
                'ordering': ['country', 'name'],
                'unique_together': {('country', 'name')},
            },
        ),
        migrations.CreateModel(
            name='POI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(help_text='URL-friendly version of the name', max_length=255, unique=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False, help_text='Featured in suggested content catalog')),
                ('featured_order', models.IntegerField(default=0, help_text='Display order for featured content (higher = more prominent)')),
                ('name', models.CharField(max_length=200)),
                ('poi_type', models.CharField(choices=[('landmark', 'Landmark'), ('museum', 'Museum'), ('park', 'Park/Garden'), ('beach', 'Beach'), ('mountain', 'Mountain'), ('temple', 'Temple/Religious Site'), ('historical', 'Historical Site'), ('viewpoint', 'Viewpoint'), ('entertainment', 'Entertainment'), ('shopping', 'Shopping'), ('nightlife', 'Nightlife'), ('nature', 'Nature Reserve'), ('other', 'Other')], default='landmark', max_length=20)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('entry_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Entry fee in local currency', max_digits=8, null=True)),
                ('entry_fee_currency', models.CharField(blank=True, max_length=3)),
                ('opening_hours', models.JSONField(blank=True, default=dict, help_text='Opening hours by day of week')),
                ('typical_duration', models.IntegerField(blank=True, help_text='Typical visit duration in minutes', null=True)),
                ('wheelchair_accessible', models.BooleanField(default=False)),
                ('parking_available', models.BooleanField(default=False)),
                ('visitor_count', models.IntegerField(default=0)),
                ('average_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('review_count', models.IntegerField(default=0)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pois', to='locations.city')),
            ],
            options={
                'verbose_name': 'POI',
                'verbose_name_plural': 'POIs',
                'db_table': 'locations_pois',
                'ordering': ['city', 'name'],
                'indexes': [models.Index(fields=['poi_type'], name='locations_p_poi_typ_99e728_idx'), models.Index(fields=['latitude', 'longitude'], name='locations_p_latitud_2adc3a_idx')],
            },
        ),
    ]
