# Generated by Django 6.0.1 on 2026-01-22 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_city_capital_type_city_elevation_city_is_capital'),
    ]

    operations = [
        migrations.AddField(
            model_name='poi',
            name='elevation',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Elevation of the City in feet', max_digits=9, null=True),
        ),
    ]
