# Generated by Django 6.0.1 on 2026-01-24 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_poi_elevation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='elevation',
        ),
        migrations.RemoveField(
            model_name='poi',
            name='elevation',
        ),
        migrations.AddField(
            model_name='city',
            name='elevation_m',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Elevation of the City in meters', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='poi',
            name='elevation_m',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Elevation of the POI in meters', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='flag_emoji',
            field=models.CharField(blank=True, help_text='Unicode flag emoji (e.g., 🇺🇸)', max_length=10),
        ),
    ]
