# Generated by Django 6.0.1 on 2026-01-25 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_remove_city_elevation_remove_poi_elevation_and_more'),
        ('media_app', '0002_remove_mediaalbum_media_count_alter_media_media_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='featured_media',
            field=models.ForeignKey(blank=True, help_text='Featured image or video for this location', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_for_%(class)s', to='media_app.media'),
        ),
        migrations.AddField(
            model_name='city',
            name='review_notes',
            field=models.TextField(blank=True, help_text='Notes from reviewer'),
        ),
        migrations.AddField(
            model_name='city',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='city',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_changes', 'Needs Changes')], default='approved', help_text='Review status of this location', max_length=20),
        ),
        migrations.AddField(
            model_name='city',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='country',
            name='featured_media',
            field=models.ForeignKey(blank=True, help_text='Featured image or video for this location', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_for_%(class)s', to='media_app.media'),
        ),
        migrations.AddField(
            model_name='country',
            name='review_notes',
            field=models.TextField(blank=True, help_text='Notes from reviewer'),
        ),
        migrations.AddField(
            model_name='country',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='country',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_changes', 'Needs Changes')], default='approved', help_text='Review status of this location', max_length=20),
        ),
        migrations.AddField(
            model_name='country',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='poi',
            name='featured_media',
            field=models.ForeignKey(blank=True, help_text='Featured image or video for this location', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_for_%(class)s', to='media_app.media'),
        ),
        migrations.AddField(
            model_name='poi',
            name='review_notes',
            field=models.TextField(blank=True, help_text='Notes from reviewer'),
        ),
        migrations.AddField(
            model_name='poi',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poi',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='poi',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_changes', 'Needs Changes')], default='approved', help_text='Review status of this location', max_length=20),
        ),
        migrations.AddField(
            model_name='poi',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='region',
            name='featured_media',
            field=models.ForeignKey(blank=True, help_text='Featured image or video for this location', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_for_%(class)s', to='media_app.media'),
        ),
        migrations.AddField(
            model_name='region',
            name='review_notes',
            field=models.TextField(blank=True, help_text='Notes from reviewer'),
        ),
        migrations.AddField(
            model_name='region',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='region',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_changes', 'Needs Changes')], default='approved', help_text='Review status of this location', max_length=20),
        ),
        migrations.AddField(
            model_name='region',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['status', '-created_at'], name='locations_c_status_e90b13_idx'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['status', '-created_at'], name='locations_c_status_c523cf_idx'),
        ),
        migrations.AddIndex(
            model_name='poi',
            index=models.Index(fields=['status', '-created_at'], name='locations_p_status_3e7522_idx'),
        ),
        migrations.AddIndex(
            model_name='region',
            index=models.Index(fields=['status', '-created_at'], name='locations_r_status_61c501_idx'),
        ),
    ]
