# Generated by Django 6.0.1 on 2026-01-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_migrate_to_approval_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='approval_priority',
            field=models.CharField(choices=[('low', 'Low Priority'), ('normal', 'Normal'), ('high', 'High Priority'), ('urgent', 'Urgent')], default='normal', help_text='Priority in review queue', max_length=10),
        ),
        migrations.AddField(
            model_name='city',
            name='approval_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('changes_requested', 'Changes Requested'), ('archived', 'Archived')], db_index=True, default='draft', help_text='Current approval status', max_length=20),
        ),
        migrations.AddField(
            model_name='city',
            name='submitted_at',
            field=models.DateTimeField(blank=True, help_text='When content was submitted for review', null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='approval_priority',
            field=models.CharField(choices=[('low', 'Low Priority'), ('normal', 'Normal'), ('high', 'High Priority'), ('urgent', 'Urgent')], default='normal', help_text='Priority in review queue', max_length=10),
        ),
        migrations.AddField(
            model_name='country',
            name='approval_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('changes_requested', 'Changes Requested'), ('archived', 'Archived')], db_index=True, default='draft', help_text='Current approval status', max_length=20),
        ),
        migrations.AddField(
            model_name='country',
            name='submitted_at',
            field=models.DateTimeField(blank=True, help_text='When content was submitted for review', null=True),
        ),
        migrations.AddField(
            model_name='poi',
            name='approval_priority',
            field=models.CharField(choices=[('low', 'Low Priority'), ('normal', 'Normal'), ('high', 'High Priority'), ('urgent', 'Urgent')], default='normal', help_text='Priority in review queue', max_length=10),
        ),
        migrations.AddField(
            model_name='poi',
            name='approval_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('changes_requested', 'Changes Requested'), ('archived', 'Archived')], db_index=True, default='draft', help_text='Current approval status', max_length=20),
        ),
        migrations.AddField(
            model_name='poi',
            name='submitted_at',
            field=models.DateTimeField(blank=True, help_text='When content was submitted for review', null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='approval_priority',
            field=models.CharField(choices=[('low', 'Low Priority'), ('normal', 'Normal'), ('high', 'High Priority'), ('urgent', 'Urgent')], default='normal', help_text='Priority in review queue', max_length=10),
        ),
        migrations.AddField(
            model_name='region',
            name='approval_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('changes_requested', 'Changes Requested'), ('archived', 'Archived')], db_index=True, default='draft', help_text='Current approval status', max_length=20),
        ),
        migrations.AddField(
            model_name='region',
            name='submitted_at',
            field=models.DateTimeField(blank=True, help_text='When content was submitted for review', null=True),
        ),
    ]
