# Generated by Django 6.0.1 on 2026-01-30 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_city_approval_priority_city_approval_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='poi_count',
        ),
        migrations.RemoveField(
            model_name='country',
            name='city_count',
        ),
        migrations.RemoveField(
            model_name='country',
            name='poi_count',
        ),
        migrations.RemoveField(
            model_name='region',
            name='city_count',
        ),
    ]
