# Generated by Django 6.1.1 on 2026-09-29 20:21

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveSmallIntegerField()),
                ('date', models.DateField()),
                ('theme', models.CharField(blank=True, help_text='One-line summary of the day', max_length=200)),
                ('meals_included', models.BooleanField(default=False, help_text='Meals are already covered by the trip price')),
            ],
            options={
                'ordering': ['trip', 'day_number'],
            },
        ),
        migrations.CreateModel(
            name='Traveler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('home_airport', models.CharField(blank=True, help_text='IATA code, e.g. BOS', max_length=8)),
                ('dietary_notes', models.TextField(blank=True)),
                ('mobility_notes', models.TextField(blank=True)),
                ('passport_country', models.CharField(blank=True, help_text='ISO 3166-1 alpha-2, e.g. US', max_length=2)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack'), ('drinks', 'Drinks')], max_length=16)),
                ('cuisine', models.CharField(blank=True, max_length=100)),
                ('price_range', models.CharField(blank=True, choices=[('$', '$'), ('$$', '$$'), ('$$$', '$$$'), ('$$$$', '$$$$')], max_length=8)),
                ('why_recommended', models.TextField(blank=True)),
                ('reservation_notes', models.TextField(blank=True, help_text='How to book, when to book, booking reference')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='trips.day')),
            ],
            options={
                'ordering': ['day', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('destination', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('budget', models.CharField(blank=True, choices=[('budget', 'Budget'), ('moderate', 'Moderate'), ('premium', 'Premium'), ('luxury', 'Luxury')], max_length=16)),
                ('structure', models.CharField(blank=True, choices=[('guided', 'Guided'), ('semi_guided', 'Semi-guided'), ('self_directed', 'Self-directed')], max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('travelers', models.ManyToManyField(blank=True, related_name='trips', to='trips.traveler')),
            ],
            options={
                'ordering': ['-start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Lodging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True)),
                ('confirmation_number', models.CharField(blank=True, max_length=40)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('nightly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('notes', models.TextField(blank=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lodging', to='trips.trip')),
            ],
            options={
                'verbose_name_plural': 'lodging',
                'ordering': ['check_in'],
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.CharField(blank=True, max_length=120)),
                ('flight_number', models.CharField(blank=True, max_length=20)),
                ('confirmation_number', models.CharField(blank=True, max_length=40)),
                ('origin', models.CharField(blank=True, help_text='IATA code', max_length=8)),
                ('destination', models.CharField(blank=True, help_text='IATA code', max_length=8)),
                ('departure_at', models.DateTimeField()),
                ('arrival_at', models.DateTimeField()),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('notes', models.TextField(blank=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='trips.trip')),
            ],
            options={
                'verbose_name_plural': 'flights',
                'ordering': ['departure_at'],
            },
        ),
        migrations.AddField(
            model_name='day',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='trips.trip'),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='trips.trip')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Confirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="What this is, e.g. 'Hotel' or 'Airport transfer'", max_length=200)),
                ('confirmation_number', models.CharField(max_length=60)),
                ('provider', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='trips.trip')),
            ],
            options={
                'verbose_name_plural': 'confirmations',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('phase', 'Phase'), ('logistics_table', 'Logistics table'), ('callout', 'Callout'), ('choose_your_adventure', 'Choose your adventure'), ('free_text', 'Free text')], max_length=32)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('icon', models.CharField(blank=True, max_length=32)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('content', models.JSONField(default=dict)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='trips.day')),
            ],
            options={
                'ordering': ['day', 'order', 'id'],
                'indexes': [models.Index(fields=['day', 'order'], name='trips_secti_day_id_2a5dd1_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['start_date'], name='trips_trip_start_d_d83967_idx'),
        ),
        migrations.AddConstraint(
            model_name='day',
            constraint=models.UniqueConstraint(fields=('trip', 'day_number'), name='unique_day_number_per_trip'),
        ),
    ]
