# Generated by Django 6.1.1 on 2026-09-29 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_mark_booked_trip_ready_to_go'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='travelers',
            field=models.ManyToManyField(blank=True, help_text='Leave blank if the whole group is together. Set it only when this day splits the trip up.', related_name='days', to='trips.traveler'),
        ),
    ]
