"""Rename Flight to TransportLeg and teach it modes beyond air.

Hand-written rather than autogenerated: `makemigrations` sees too much of the
field definitions change and proposes deleting `Flight` and creating
`TransportLeg`, which would drop the four existing legs on the floor. The
table rename below keeps the rows.

`mode` defaults to `plane` because every leg that exists today is a flight, so
existing data is correct without a separate data migration.
"""

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0005_day_travelers"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Flight",
            new_name="TransportLeg",
        ),
        migrations.AlterModelOptions(
            name="transportleg",
            options={
                "ordering": ["trip", "departure_at"],
                "verbose_name_plural": "transport legs",
            },
        ),
        migrations.AddField(
            model_name="transportleg",
            name="mode",
            field=models.CharField(
                choices=[
                    ("plane", "Flight"),
                    ("train", "Train"),
                    ("pov", "Private vehicle"),
                    ("rental_car", "Rental car"),
                    ("walking", "Walking"),
                    ("other", "Other"),
                ],
                default="plane",
                max_length=12,
            ),
        ),
        # IATA codes are 3 characters, but a train leg has stations and a drive
        # has towns, so the columns are sized for whatever the mode needs.
        migrations.AlterField(
            model_name="transportleg",
            name="origin",
            field=models.CharField(
                blank=True, help_text="Airport code, station, or town", max_length=120
            ),
        ),
        migrations.AlterField(
            model_name="transportleg",
            name="destination",
            field=models.CharField(
                blank=True, help_text="Airport code, station, or town", max_length=120
            ),
        ),
        migrations.AlterField(
            model_name="transportleg",
            name="trip",
            field=models.ForeignKey(
                on_delete=models.deletion.CASCADE,
                related_name="transport",
                to="trips.trip",
            ),
        ),
    ]
