# Generated by Django 6.1.1 on 2026-09-30 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_rename_flight_to_transportleg'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TripGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='trips.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'trip grant',
                'verbose_name_plural': 'trip grants',
                'ordering': ['trip', 'user'],
                'constraints': [models.UniqueConstraint(fields=('trip', 'user'), name='unique_trip_grant')],
            },
        ),
    ]
