# Generated by Django 6.1.1 on 2026-09-30 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_tripgrant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, help_text='Set when the trip is created in the app. Left blank for trips authored in the admin.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_trips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trip',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, help_text='Set when the trip is deleted. A deleted trip is hidden everywhere but is never removed, so it can be restored.', null=True),
        ),
    ]
