# Generated by Django 6.1.1 on 2026-10-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0009_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='public_token',
            field=models.UUIDField(blank=True, db_index=True, editable=False, help_text='Unguessable key for the public, non-detailed view of this trip. Blank means no public page exists — clearing it revokes the link without touching the trip.', null=True, unique=True),
        ),
    ]
