# Generated by Django 6.1.1 on 2026-10-06 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def link_existing_accounts(apps, schema_editor):
    """Turn the accounts that already exist into travelers.

    The same rule the live signal in ``trips.signals`` applies: match by
    the account's full name (falling back to the username) and only when the
    match is unique, create a row when the roster does not know the person,
    and leave an ambiguous name alone for ``dedupe_travelers`` rather than
    guess which row holds someone's trips.
    """
    User = apps.get_model(settings.AUTH_USER_MODEL)
    Traveler = apps.get_model("trips", "Traveler")
    for user in User.objects.all():
        if Traveler.objects.filter(user=user).exists():
            continue
        name = f"{user.first_name} {user.last_name}".strip() or user.username
        matches = list(
            Traveler.objects.filter(name=name, user__isnull=True)
            .order_by("pk")
            .values_list("pk", flat=True)
        )
        if len(matches) == 1:
            Traveler.objects.filter(pk=matches[0], user__isnull=True).update(
                user=user
            )
        elif not matches:
            Traveler.objects.create(name=name, user=user)


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0011_transportleg_operator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='traveler',
            name='user',
            field=models.OneToOneField(blank=True, help_text='The account this person signs in with, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traveler', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(link_existing_accounts, migrations.RunPython.noop),
    ]
