# Generated by Django 6.1.2 on 2026-10-07 18:56
#
# Moves the role from the app-wide accounts.UserRole onto each TripGrant.
# The data step keeps everyone's effective access unchanged:
#
# * each grant takes its holder's strongest app-wide role, with ``creator``
#   becoming ``editor`` (creator was editor-plus-create; "create" stays
#   app-wide on UserRole);
# * a grant held by a non-staff user with no role gave no access before (read
#   needed a grant *and* a role), so it is deleted rather than silently turned
#   into read access;
# * every UserRole row except ``creator`` is then deleted — those roles now live
#   on the grants.

from django.db import migrations, models


# Strongest first, as accounts.ROLE_LADDER was before this migration.
LADDER = ["creator", "editor", "commentor", "viewer"]
TO_GRANT_ROLE = {"creator": "editor", "editor": "editor", "commentor": "commentor", "viewer": "viewer"}


def roles_onto_grants(apps, schema_editor):
    TripGrant = apps.get_model("trips", "TripGrant")
    UserRole = apps.get_model("accounts", "UserRole")

    held = {}
    for user_id, role in UserRole.objects.values_list("user_id", "role"):
        held.setdefault(user_id, set()).add(role)

    for grant in TripGrant.objects.select_related("user"):
        roles = held.get(grant.user_id)
        if roles:
            strongest = min(roles, key=LADDER.index)
            grant.role = TO_GRANT_ROLE[strongest]
            grant.save(update_fields=["role"])
        elif not (grant.user.is_staff or grant.user.is_superuser):
            grant.delete()
        # Staff with no role keep the default ``viewer``; staff need no grant.

    UserRole.objects.exclude(role="creator").delete()


def grants_onto_roles(apps, schema_editor):
    """Best-effort reverse: each user's strongest grant role becomes app-wide."""
    TripGrant = apps.get_model("trips", "TripGrant")
    UserRole = apps.get_model("accounts", "UserRole")
    strongest = {}
    for user_id, role in TripGrant.objects.values_list("user_id", "role"):
        current = strongest.get(user_id)
        if current is None or LADDER.index(role) < LADDER.index(current):
            strongest[user_id] = role
    for user_id, role in strongest.items():
        UserRole.objects.get_or_create(user_id=user_id, role=role)


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0013_traveler_profile'),
        ('accounts', '0013_userrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripgrant',
            name='role',
            field=models.CharField(choices=[('viewer', 'Viewer'), ('commentor', 'Commentor'), ('editor', 'Editor')], default='viewer', help_text='What this person may do on this trip.', max_length=16),
        ),
        migrations.RunPython(roles_onto_grants, grants_onto_roles),
    ]
