# Generated by Django 6.0 on 2026-01-06 17:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(help_text='URL-friendly version of the name', max_length=255, unique=True)),
                ('name', models.CharField(help_text='E.g., Adventure, Cultural, Food & Drink', max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Icon name or emoji', max_length=50)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Activity Categories',
                'db_table': 'activities_categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(help_text='URL-friendly version of the name', max_length=255, unique=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False, help_text='Featured in suggested content catalog')),
                ('featured_order', models.IntegerField(default=0, help_text='Display order for featured content (higher = more prominent)')),
                ('name', models.CharField(help_text='E.g., Skydiving, Wine Tasting, Scuba Diving', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the activity')),
                ('short_description', models.CharField(blank=True, help_text='Brief description for cards/lists', max_length=300)),
                ('skill_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='beginner', max_length=20)),
                ('fitness_required', models.IntegerField(default=1, help_text='1=Low, 5=Very High physical fitness required', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('age_minimum', models.IntegerField(blank=True, help_text='Minimum age to participate', null=True)),
                ('age_maximum', models.IntegerField(blank=True, help_text='Maximum age to participate', null=True)),
                ('typical_duration', models.IntegerField(blank=True, help_text='Typical duration in minutes', null=True)),
                ('duration_category', models.CharField(choices=[('quick', 'Quick (< 1 hour)'), ('short', 'Short (1-3 hours)'), ('half_day', 'Half Day (3-5 hours)'), ('full_day', 'Full Day (5-8 hours)'), ('multi_day', 'Multi-Day')], default='short', max_length=20)),
                ('estimated_cost_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum estimated cost in USD', max_digits=10, null=True)),
                ('estimated_cost_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum estimated cost in USD', max_digits=10, null=True)),
                ('cost_level', models.CharField(choices=[('free', 'Free'), ('budget', 'Budget ($)'), ('moderate', 'Moderate ($$)'), ('expensive', 'Expensive ($$$)'), ('luxury', 'Luxury ($$$$)')], default='moderate', max_length=20)),
                ('best_for', models.CharField(choices=[('solo', 'Best Solo'), ('couple', 'Romantic/Couples'), ('family', 'Family Friendly'), ('group', 'Group Activity'), ('any', 'Any Group Size')], default='any', max_length=20)),
                ('best_season', models.JSONField(default=list, help_text='List of best seasons for this activity')),
                ('indoor_outdoor', models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor'), ('both', 'Both')], default='outdoor', max_length=20)),
                ('equipment_needed', models.TextField(blank=True, help_text='List of equipment/gear needed')),
                ('booking_required', models.BooleanField(default=False, help_text='Whether advance booking is typically required')),
                ('guide_required', models.BooleanField(default=False, help_text='Whether a guide is typically required')),
                ('wheelchair_accessible', models.BooleanField(default=False)),
                ('suitable_for_children', models.BooleanField(default=True)),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('moderate', 'Moderate Risk'), ('high', 'High Risk'), ('extreme', 'Extreme Risk')], default='low', max_length=20)),
                ('safety_notes', models.TextField(blank=True, help_text='Important safety information')),
                ('popularity_score', models.IntegerField(default=0, help_text='Calculated popularity score')),
                ('bucket_list_count', models.IntegerField(default=0, help_text='How many times added to bucket lists')),
                ('completed_count', models.IntegerField(default=0, help_text='How many times marked as completed')),
                ('average_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('review_count', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='activities.activitycategory')),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'db_table': 'activities',
                'ordering': ['-popularity_score', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ActivityTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(help_text='URL-friendly version of the name', max_length=255, unique=True)),
                ('name', models.CharField(help_text='E.g., outdoor, adrenaline, cultural, romantic', max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('usage_count', models.IntegerField(default=0, help_text='How many activities use this tag')),
                ('activities', models.ManyToManyField(blank=True, related_name='tags', to='activities.activity')),
            ],
            options={
                'db_table': 'activity_tags',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['category', 'skill_level'], name='activities_categor_d95c03_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['cost_level'], name='activities_cost_le_16425a_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['-popularity_score'], name='activities_popular_da2f34_idx'),
        ),
    ]
