# Generated by Django 6.0.1 on 2026-01-30 22:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivityBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Personal notes about this activity')),
                ('interest_level', models.IntegerField(default=5, help_text='1=Mild Interest, 5=Really Want To Do', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
            options={
                'db_table': 'user_activity_bookmarks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-created_at'], 'permissions': [('can_approve_activities', 'Can approve user-submitted activities'), ('can_bypass_approval', 'Can create pre-approved activities')], 'verbose_name_plural': 'Activities'},
        ),
        migrations.RemoveIndex(
            model_name='activity',
            name='activities_categor_d95c03_idx',
        ),
        migrations.RemoveIndex(
            model_name='activity',
            name='activities_cost_le_16425a_idx',
        ),
        migrations.AddField(
            model_name='activity',
            name='approval_priority',
            field=models.CharField(choices=[('low', 'Low Priority'), ('normal', 'Normal'), ('high', 'High Priority'), ('urgent', 'Urgent')], default='normal', help_text='Priority in review queue', max_length=10),
        ),
        migrations.AddField(
            model_name='activity',
            name='approval_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('changes_requested', 'Changes Requested'), ('archived', 'Archived')], db_index=True, default='draft', help_text='Current approval status', max_length=20),
        ),
        migrations.AddField(
            model_name='activity',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this activity', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='event_count',
            field=models.IntegerField(default=0, help_text='How many events created from this activity'),
        ),
        migrations.AddField(
            model_name='activity',
            name='rejection_notes',
            field=models.TextField(blank=True, help_text='Staff notes on why this was rejected (visible to creator)'),
        ),
        migrations.AddField(
            model_name='activity',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, help_text='When content was reviewed', null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who reviewed this content', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='source',
            field=models.CharField(choices=[('user', 'User Created'), ('staff', 'Staff Created'), ('import', 'Imported')], default='user', help_text='How this activity was created', max_length=20),
        ),
        migrations.AddField(
            model_name='activity',
            name='specificity_level',
            field=models.CharField(choices=[('general', 'General - e.g., "Go to a concert"'), ('specific', 'Specific - e.g., "See Kenny Chesney at Vegas Sphere"'), ('very_specific', 'Very Specific - includes dates/times')], default='general', help_text='How specific is this activity description?', max_length=20),
        ),
        migrations.AddField(
            model_name='activity',
            name='submitted_at',
            field=models.DateTimeField(blank=True, help_text='When content was submitted for review', null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='submitted_by',
            field=models.ForeignKey(blank=True, help_text='User who submitted this content', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='suggested_date_range_end',
            field=models.DateField(blank=True, help_text='Suggested end of date range', null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='suggested_date_range_start',
            field=models.DateField(blank=True, help_text='Suggested start of date range', null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='suggested_location',
            field=models.CharField(blank=True, help_text="Suggested location (e.g., 'Vegas Sphere')", max_length=200),
        ),
        migrations.AddField(
            model_name='activity',
            name='suggested_timeframe',
            field=models.CharField(blank=True, help_text="Suggested timeframe (e.g., 'Summer 2026')", max_length=200),
        ),
        migrations.AddField(
            model_name='activity',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private - Only I can see'), ('public', 'Public - Everyone can see (requires approval)')], default='private', help_text='Who can see this activity', max_length=20),
        ),
        migrations.AddField(
            model_name='activitycategory',
            name='allow_user_submissions',
            field=models.BooleanField(default=True, help_text='Allow regular users to submit activities in this category'),
        ),
        migrations.AddField(
            model_name='activitytag',
            name='user_can_add',
            field=models.BooleanField(default=True, help_text='Whether regular users can add this tag to activities'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='best_season',
            field=models.JSONField(blank=True, default=list, help_text='List of best seasons for this activity'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='cost_level',
            field=models.CharField(choices=[('free', 'Free'), ('budget', 'Budget ($)'), ('moderate', 'Moderate ($$)'), ('expensive', 'Expensive ($$$)'), ('luxury', 'Luxury ($$$$)'), ('varies', 'Varies')], default='varies', max_length=20),
        ),
        migrations.AlterField(
            model_name='activity',
            name='duration_category',
            field=models.CharField(choices=[('quick', 'Quick (< 1 hour)'), ('short', 'Short (1-3 hours)'), ('half_day', 'Half Day (3-5 hours)'), ('full_day', 'Full Day (5-8 hours)'), ('multi_day', 'Multi-Day'), ('varies', 'Varies')], default='varies', max_length=20),
        ),
        migrations.AlterField(
            model_name='activity',
            name='indoor_outdoor',
            field=models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor'), ('both', 'Both'), ('either', 'Either/Not Specified')], default='either', max_length=20),
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(help_text="E.g., 'See Kenny Chesney concert' or 'Go skydiving' or 'Visit a museum'", max_length=200),
        ),
        migrations.AlterField(
            model_name='activity',
            name='skill_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert'), ('any', 'Any Level')], default='any', max_length=20),
        ),
        migrations.AlterField(
            model_name='activity',
            name='suitable_for_children',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='wheelchair_accessible',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['category', 'approval_status'], name='activities_categor_71f354_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['created_by', 'visibility'], name='activities_created_e3cb24_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['visibility', 'approval_status'], name='activities_visibil_3595f3_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['source'], name='activities_source_21287e_idx'),
        ),
        migrations.AddField(
            model_name='useractivitybookmark',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='activities.activity'),
        ),
        migrations.AddField(
            model_name='useractivitybookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_bookmarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='useractivitybookmark',
            unique_together={('user', 'activity')},
        ),
    ]
