# Generated by Django 6.0.1 on 2026-01-31 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_alter_activity_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='risk_level',
            field=models.CharField(choices=[('low', 'Low Risk'), ('moderate', 'Moderate Risk'), ('high', 'High Risk'), ('extreme', 'Extreme Risk')], default='low', help_text='Risk level of this activity', max_length=20),
        ),
    ]
