# Generated by Django 6.1.2 on 2026-10-08 17:47

from django.db import migrations
from django.utils.text import slugify

# One category list shared by activities and events (events.0005 points Event at
# these). Same names, icons and order as the event categories seeded in events.0003.
SHARED = [
    ("Music", "bi-music-note-beamed"), ("Festival", "bi-stars"), ("Sports", "bi-trophy"),
    ("Food & Drink", "bi-cup-hot"), ("Arts & Culture", "bi-palette"), ("Outdoors", "bi-tree"),
    ("Community", "bi-people"), ("Nightlife", "bi-moon-stars"), ("Other", "bi-calendar-event"),
]


def forwards(apps, schema_editor):
    ActivityCategory = apps.get_model("activities", "ActivityCategory")
    Activity = apps.get_model("activities", "Activity")
    for order, (name, icon) in enumerate(SHARED):
        ActivityCategory.objects.get_or_create(
            name=name,
            defaults={"slug": slugify(name), "icon": icon, "display_order": order,
                      "is_active": True, "allow_user_submissions": True},
        )
    # "Concert" was the only category so far: re-file its activities and retire it.
    concert = ActivityCategory.objects.filter(name="Concert").first()
    if concert:
        music = ActivityCategory.objects.get(name="Music")
        festival = ActivityCategory.objects.get(name="Festival")
        Activity.objects.filter(category=concert, name__iexact="Oktoberfest").update(category=festival)
        Activity.objects.filter(category=concert).update(category=music)
        if not Activity.objects.filter(category=concert).exists():
            concert.delete()


def backwards(apps, schema_editor):
    """Recreate Concert and move Music/Festival activities back; leave the new rows."""
    ActivityCategory = apps.get_model("activities", "ActivityCategory")
    Activity = apps.get_model("activities", "Activity")
    concert, _ = ActivityCategory.objects.get_or_create(name="Concert", defaults={"slug": "concert"})
    Activity.objects.filter(category__name__in=["Music", "Festival"]).update(category=concert)


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_alter_activity_specificity_level'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
