# Generated by Django 6.1.2 on 2026-10-08 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_shared_categories'),
        ('locations', '0009_alter_poi_poi_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='city',
            field=models.ForeignKey(blank=True, help_text='City it happens in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='locations.city'),
        ),
        migrations.AddField(
            model_name='activity',
            name='country',
            field=models.ForeignKey(blank=True, help_text='Country it happens in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='locations.country'),
        ),
        migrations.AddField(
            model_name='activity',
            name='recurrence',
            field=models.CharField(choices=[('anytime', 'Any time'), ('yearly', 'Every year'), ('seasonal', 'Several times a year'), ('once', 'One-off')], default='anytime', help_text='How often it happens', max_length=12),
        ),
        migrations.AddField(
            model_name='activity',
            name='region',
            field=models.ForeignKey(blank=True, help_text='Region / state it happens in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='locations.region'),
        ),
        migrations.AddField(
            model_name='activity',
            name='usual_months',
            field=models.JSONField(blank=True, default=list, help_text='Months it usually happens in (1-12)'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='suggested_location',
            field=models.CharField(blank=True, help_text="Place, if it isn't in our list of cities (e.g., 'Vegas Sphere')", max_length=200),
        ),
        migrations.AlterField(
            model_name='activity',
            name='suggested_timeframe',
            field=models.CharField(blank=True, help_text="Timing notes (e.g., 'Mid September to the first Sunday in October')", max_length=200),
        ),
    ]
