# Generated by Django 6.1.2 on 2026-10-09 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0010_link_suggested_locations'),
        ('media_app', '0002_remove_mediaalbum_media_count_alter_media_media_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='featured_media',
            field=models.ForeignKey(blank=True, help_text='Picture shown on its page and in lists', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_for_activity', to='media_app.media'),
        ),
    ]
