# Generated by Django 6.1.2 on 2026-10-10 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0011_featured_media'),
        ('locations', '0009_alter_poi_poi_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='venue',
            field=models.ForeignKey(blank=True, help_text='Where it takes place, e.g. a stadium (fills in the city)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='locations.poi'),
        ),
    ]
