# Generated by Django 6.0 on 2026-01-06 21:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('events', '0001_initial'),
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BucketListCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="E.g., 'Adventure Goals', 'European Cities', 'Food Experiences'", max_length=100)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#3B82F6', help_text='Hex color code for visual organization', max_length=7)),
                ('icon', models.CharField(blank=True, help_text='Icon name or emoji', max_length=50)),
                ('display_order', models.IntegerField(default=0)),
                ('item_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bucket_list_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Bucket List Categories',
                'db_table': 'bucket_list_categories',
                'ordering': ['user', 'display_order', 'name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='BucketListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_title', models.CharField(blank=True, help_text='For custom bucket list items not in catalog', max_length=200)),
                ('custom_description', models.TextField(blank=True, help_text='Description for custom items')),
                ('personal_notes', models.TextField(blank=True, help_text='Personal notes, reasons, memories')),
                ('target_date', models.DateField(blank=True, help_text='When user hopes to complete this', null=True)),
                ('target_season', models.CharField(choices=[('spring', 'Spring'), ('summer', 'Summer'), ('fall', 'Fall'), ('winter', 'Winter'), ('anytime', 'Anytime')], default='anytime', help_text='Best time to do this', max_length=20)),
                ('estimated_budget', models.DecimalField(blank=True, decimal_places=2, help_text="User's estimated budget in their currency", max_digits=10, null=True)),
                ('budget_currency', models.CharField(default='USD', max_length=3)),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Very High'), (5, 'Must Do!')], default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('status', models.CharField(choices=[('wishlist', 'Wishlist'), ('researching', 'Researching'), ('planning', 'Planning'), ('booked', 'Booked'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], db_index=True, default='wishlist', max_length=20)),
                ('completed_date', models.DateField(blank=True, help_text='When user completed this item', null=True)),
                ('completion_notes', models.TextField(blank=True, help_text='Thoughts/reflections after completing')),
                ('user_rating', models.IntegerField(blank=True, help_text="User's rating after completing", null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('is_public', models.BooleanField(default=True, help_text='Whether this item is visible to others')),
                ('with_who', models.CharField(blank=True, help_text='Who user wants to do this with', max_length=100)),
                ('inspiration_source', models.CharField(blank=True, help_text='Where they got the idea (friend, blog, movie, etc.)', max_length=200)),
                ('reminder_enabled', models.BooleanField(default=False, help_text='Send reminders about this item')),
                ('next_reminder_date', models.DateField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list, help_text="User's custom tags")),
                ('display_order', models.IntegerField(default=0, help_text="User's custom ordering")),
                ('activity', models.ForeignKey(blank=True, help_text='Activity to experience', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bucket_list_items', to='activities.activity')),
                ('city', models.ForeignKey(blank=True, help_text='City/destination to visit', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bucket_list_items', to='locations.city')),
                ('event', models.ForeignKey(blank=True, help_text='Event to attend', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bucket_list_items', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bucket_list_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bucket_list_items',
                'ordering': ['user', '-priority', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='BucketListItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_memberships', to='bucketlists.bucketlistcategory')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_memberships', to='bucketlists.bucketlistitem')),
            ],
            options={
                'db_table': 'bucket_list_item_categories',
            },
        ),
        migrations.CreateModel(
            name='BucketListMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('milestone_type', models.CharField(choices=[('items_added', 'Items Added'), ('items_completed', 'Items Completed'), ('countries_visited', 'Countries Visited'), ('activities_completed', 'Activities Completed'), ('events_attended', 'Events Attended'), ('custom', 'Custom Milestone')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('target_count', models.IntegerField(help_text='Target number to achieve')),
                ('current_count', models.IntegerField(default=0, help_text='Current progress')),
                ('is_achieved', models.BooleanField(default=False)),
                ('achieved_date', models.DateTimeField(blank=True, null=True)),
                ('badge_icon', models.CharField(blank=True, max_length=50)),
                ('badge_color', models.CharField(default='#10B981', max_length=7)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bucket_list_milestones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bucket_list_milestones',
                'ordering': ['user', '-is_achieved', 'milestone_type'],
            },
        ),
        migrations.AddIndex(
            model_name='bucketlistitem',
            index=models.Index(fields=['user', 'status'], name='bucket_list_user_id_468171_idx'),
        ),
        migrations.AddIndex(
            model_name='bucketlistitem',
            index=models.Index(fields=['user', '-priority'], name='bucket_list_user_id_3e84a2_idx'),
        ),
        migrations.AddIndex(
            model_name='bucketlistitem',
            index=models.Index(fields=['status', 'target_date'], name='bucket_list_status_7e990a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bucketlistitemcategory',
            unique_together={('item', 'category')},
        ),
    ]
