# Generated by Django 6.0 on 2026-01-07 17:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="E.g., 'Similar Activities', 'Popular in City'", max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('rule_type', models.CharField(choices=[('content_based', 'Content-Based'), ('collaborative', 'Collaborative Filtering'), ('popularity', 'Popularity-Based'), ('location_based', 'Location-Based'), ('user_preference', 'User Preference'), ('trending', 'Trending'), ('seasonal', 'Seasonal'), ('custom', 'Custom Logic')], max_length=20)),
                ('base_score', models.IntegerField(default=50, help_text='Base relevance score (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, help_text='Weight multiplier for this rule', max_digits=5)),
                ('conditions', models.JSONField(blank=True, default=dict, help_text='Conditions that must be met for rule to apply')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this rule is currently active')),
                ('max_recommendations', models.IntegerField(default=10, help_text='Maximum recommendations to generate')),
                ('priority', models.IntegerField(default=0, help_text='Higher priority rules are evaluated first')),
                ('usage_count', models.IntegerField(default=0, help_text='How many times this rule has been used')),
                ('average_ctr', models.DecimalField(decimal_places=4, default=0.0, help_text='Average click-through rate', max_digits=5)),
                ('source_content_type', models.ForeignKey(help_text='What triggers this recommendation (e.g., Activity, City)', on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_source_rules', to='contenttypes.contenttype')),
                ('target_content_type', models.ForeignKey(help_text='What gets recommended (e.g., Activity, Event)', on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_target_rules', to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'recommendation_rules',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField(help_text='ID of item being recommended')),
                ('context_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('relevance_score', models.DecimalField(decimal_places=2, help_text='Calculated relevance score (0-100)', max_digits=5)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Confidence in recommendation (0-100)', max_digits=5)),
                ('generation_method', models.CharField(choices=[('rule_based', 'Rule-Based'), ('ml_model', 'ML Model'), ('hybrid', 'Hybrid'), ('manual', 'Manual Curation')], default='rule_based', max_length=50)),
                ('reason', models.CharField(blank=True, help_text='Why this was recommended (shown to user)', max_length=300)),
                ('explanation_data', models.JSONField(blank=True, default=dict, help_text='Detailed explanation data')),
                ('is_viewed', models.BooleanField(default=False)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_clicked', models.BooleanField(default=False)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('dismiss_reason', models.CharField(blank=True, max_length=100)),
                ('is_saved', models.BooleanField(default=False, help_text='User saved/bookmarked this recommendation')),
                ('saved_at', models.DateTimeField(blank=True, null=True)),
                ('is_converted', models.BooleanField(default=False, help_text='User took desired action (added to bucket list, booked, etc.)')),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When recommendation becomes stale', null=True)),
                ('display_position', models.IntegerField(default=0, help_text='Position in recommendation list')),
                ('content_type', models.ForeignKey(help_text='Type of item being recommended', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('context_content_type', models.ForeignKey(blank=True, help_text='What triggered this recommendation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_contexts', to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='recommendations.recommendationrule')),
            ],
            options={
                'db_table': 'recommendations',
                'ordering': ['user', '-relevance_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('interest_score', models.DecimalField(decimal_places=2, default=50.0, help_text='Interest strength (0-100)', max_digits=5)),
                ('view_count', models.IntegerField(default=0, help_text='How many times user viewed this')),
                ('interaction_count', models.IntegerField(default=0, help_text='How many times user interacted with this')),
                ('last_interacted_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('explicit', 'Explicit (user selected)'), ('implicit', 'Implicit (behavior)'), ('profile', 'Profile preferences'), ('bucket_list', 'Bucket list items'), ('completed', 'Completed activities')], default='implicit', max_length=20)),
                ('content_type', models.ForeignKey(help_text='Type of interest (Activity, City, etc.)', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_interests',
                'ordering': ['user', '-interest_score'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feedback_type', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike'), ('not_interested', 'Not Interested'), ('already_done', 'Already Done'), ('irrelevant', 'Not Relevant'), ('helpful', 'Helpful')], max_length=20)),
                ('comment', models.TextField(blank=True, help_text='Optional feedback comment')),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='recommendations.recommendation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recommendation_feedback',
                'ordering': ['-created_at'],
                'unique_together': {('recommendation', 'user')},
            },
        ),
        migrations.CreateModel(
            name='RecommendationPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateTimeField(db_index=True)),
                ('period_end', models.DateTimeField(db_index=True)),
                ('total_generated', models.IntegerField(default=0, help_text='Total recommendations generated')),
                ('total_viewed', models.IntegerField(default=0)),
                ('total_clicked', models.IntegerField(default=0)),
                ('total_converted', models.IntegerField(default=0)),
                ('total_dismissed', models.IntegerField(default=0)),
                ('view_rate', models.DecimalField(decimal_places=4, default=0.0, help_text='Percentage viewed', max_digits=5)),
                ('click_through_rate', models.DecimalField(decimal_places=4, default=0.0, help_text='Percentage clicked', max_digits=5)),
                ('conversion_rate', models.DecimalField(decimal_places=4, default=0.0, help_text='Percentage converted', max_digits=5)),
                ('avg_relevance_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('avg_confidence_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='recommendations.recommendationrule')),
            ],
            options={
                'db_table': 'recommendation_performance',
                'ordering': ['-period_end'],
                'indexes': [models.Index(fields=['rule', '-period_end'], name='recommendat_rule_id_6d879a_idx'), models.Index(fields=['period_start', 'period_end'], name='recommendat_period__cddeac_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['user', '-created_at'], name='recommendat_user_id_e124dd_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['user', '-relevance_score'], name='recommendat_user_id_29490f_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['content_type', 'object_id'], name='recommendat_content_eb74c2_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['expires_at'], name='recommendat_expires_f19a2e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recommendation',
            unique_together={('user', 'content_type', 'object_id', 'context_content_type', 'context_object_id')},
        ),
        migrations.AddIndex(
            model_name='userinterest',
            index=models.Index(fields=['user', '-interest_score'], name='user_intere_user_id_744c29_idx'),
        ),
        migrations.AddIndex(
            model_name='userinterest',
            index=models.Index(fields=['content_type', 'object_id'], name='user_intere_content_289575_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userinterest',
            unique_together={('user', 'content_type', 'object_id')},
        ),
    ]
