# Generated by Django 6.0 on 2026-01-07 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='E.g., Trips, Bucket List, Social, System', max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(default='#3B82F6', help_text='Hex color code', max_length=7)),
                ('default_enabled', models.BooleanField(default=True, help_text='Whether this category is enabled by default for new users')),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Notification Categories',
                'db_table': 'notification_categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='E.g., trip_reminder, bucket_list_milestone, new_review', max_length=100, unique=True)),
                ('display_name', models.CharField(help_text='User-friendly name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of when this notification is sent')),
                ('title_template', models.CharField(blank=True, help_text='Template for notification title with variables', max_length=200)),
                ('message_template', models.TextField(blank=True, help_text='Template for notification message with variables')),
                ('default_email', models.BooleanField(default=True, help_text='Send email by default')),
                ('default_push', models.BooleanField(default=True, help_text='Send push notification by default')),
                ('default_in_app', models.BooleanField(default=True, help_text='Show in-app notification by default')),
                ('is_system', models.BooleanField(default=False, help_text='System notification that cannot be disabled')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='notifications.notificationcategory')),
            ],
            options={
                'db_table': 'notification_types',
                'ordering': ['category', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationDigest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('digest_type', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly')], max_length=20)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('notification_count', models.IntegerField(default=0, help_text='Number of notifications included')),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_digests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_digests',
                'ordering': ['-period_end'],
                'indexes': [models.Index(fields=['user', 'digest_type'], name='notificatio_user_id_a760cd_idx'), models.Index(fields=['is_sent', 'period_end'], name='notificatio_is_sent_283847_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template_type', models.CharField(choices=[('email_subject', 'Email Subject'), ('email_html', 'Email HTML Body'), ('email_text', 'Email Text Body'), ('push_title', 'Push Notification Title'), ('push_body', 'Push Notification Body'), ('in_app', 'In-App Notification')], max_length=20)),
                ('content', models.TextField(help_text='Template content with variables like {{user_name}}, {{trip_title}}')),
                ('version', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('available_variables', models.JSONField(blank=True, default=list, help_text='List of available template variables')),
                ('notification_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='notifications.notificationtype')),
            ],
            options={
                'db_table': 'notification_templates',
                'ordering': ['notification_type', 'template_type', '-version'],
                'unique_together': {('notification_type', 'template_type', 'version')},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='ID of related object', null=True)),
                ('action_url', models.CharField(blank=True, help_text='URL to navigate to when notification is clicked', max_length=500)),
                ('channels', models.JSONField(default=list, help_text='List of channels this notification was sent through')),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False, help_text='User has archived this notification')),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_opened', models.BooleanField(default=False)),
                ('email_opened_at', models.DateTimeField(blank=True, null=True)),
                ('push_sent', models.BooleanField(default=False)),
                ('push_sent_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_for', models.DateTimeField(blank=True, db_index=True, help_text='When notification should be sent (null = send immediately)', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional data for the notification')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When notification becomes irrelevant', null=True)),
                ('content_type', models.ForeignKey(blank=True, help_text='Type of related object', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('notification_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='notifications.notificationtype')),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notificatio_user_id_611c58_idx'), models.Index(fields=['user', 'is_read'], name='notificatio_user_id_a4dd5c_idx'), models.Index(fields=['scheduled_for'], name='notificatio_schedul_3d00b6_idx'), models.Index(fields=['notification_type', '-created_at'], name='notificatio_notific_45551b_idx')],
            },
        ),
        migrations.CreateModel(
            name='PushDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_type', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web Browser')], max_length=20)),
                ('device_token', models.CharField(help_text='Push notification token', max_length=500, unique=True)),
                ('device_name', models.CharField(blank=True, help_text='User-friendly device name', max_length=200)),
                ('app_version', models.CharField(blank=True, max_length=50)),
                ('os_version', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether device should receive notifications')),
                ('last_used_at', models.DateTimeField(auto_now=True, help_text='Last time this device was used')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'push_devices',
                'ordering': ['user', '-last_used_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='push_device_user_id_8c34d3_idx'), models.Index(fields=['device_token'], name='push_device_device__c9b903_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserNotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('push_enabled', models.BooleanField(default=True)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('frequency', models.CharField(choices=[('instant', 'Instant'), ('hourly', 'Hourly Digest'), ('daily', 'Daily Digest'), ('weekly', 'Weekly Digest'), ('never', 'Never')], default='instant', max_length=20)),
                ('quiet_hours_enabled', models.BooleanField(default=False, help_text="Don't send notifications during quiet hours")),
                ('quiet_hours_start', models.TimeField(blank=True, help_text='Start of quiet hours', null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, help_text='End of quiet hours', null=True)),
                ('notification_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to='notifications.notificationtype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_notification_preferences',
                'ordering': ['user', 'notification_type'],
                'unique_together': {('user', 'notification_type')},
            },
        ),
    ]
